image:
  file: .gitpod.dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install && cd examples/typeorm_express && npm install
    command:  >
      cd examples/typeorm_express && 
      TYPEORM_MIGRATIONS=migrations/*.ts TYPEORM_MIGRATIONS_DIR=migrations TYPEORM_MIGRATIONS_RUN=true 
      TYPEORM_LOGGING=debug TYPEORM_SYNCHRONIZE=true TYPEORM_ENTITIES=src/entities/**/*.ts 
      TYPEORM_ENTITIES_DIR=entitiies TYPEORM_URL=postgres://gitpod:gitpod@localhost/postgres 
      OAUTH_CODES_SECRET=oauth_codes_secret npm run dev:debug
  - init: sleep 25
    command: >
      x=`curl -s -S "http://localhost:3000/authorize?response_type=code&client_id=ed883c20-bf58-11eb-8529-0242ac130003&code_challenge=CUZX5qE8Wvye6kS_SasIsa8MMxacJftmWdsIA_iKp3I&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%3A76543&state=s" | sed 's/.*code=\(.*\)\&.*/\1/'` && 
       curl -d "grant_type=authorization_code&client_id=ed883c20-bf58-11eb-8529-0242ac130003&redirect_uri=http%3A%2F%2Flocalhost%3A76543&code_verifier=u1ta-MQ0e7TcpHjgz33M2DcBnOQu~aMGxuiZt0QMD1C&code=$x&client_secret=not-a-secret" http://localhost:3000/token

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
